### ISSUE TITLE
using pgfplots via Plots.jl

### ISSUE THREAD

**Issue by BeastyBlacksmith** [sisl/juliaplots.sty#2]
Is it already possible to use Plots.jl with pgfplots backend as long as I save the plots as `.tex`?
If not, what would be needed to change to get this working?

**Comment by asinghvi17** [comment]
Yep, you can do that already.  Just activate the pgfplots backend (`pgfplots()`); you may need to add the `PGFPlots` package.  

However, if you want to use PGFPlots, I'd recommend checking out PGFPlotsX.jl with Pythontex - that allows you to use a lot more of PGFPlots' features.

**Comment by BeastyBlacksmith** [comment]
Are you talking about using `PGFPlots` in general or in combination with this pythontex plugin and the corresponding `\plot` command?

More concretely, if I add 
```julia
using Plots
pgfplots()
```
to `support_code.jl` of `https://github.com/sisl/tufte_algorithms_book` will 
```latex
\begin{figure}
	\begin{jlcode}
	x = [1,2,3]
        y = [2,1,3]
	plot(x,y)
	\end{jlcode}
	\begin{center}
		\plot{fig/sample_function}
	\end{center}
\end{figure}
```
work?

**Comment by asinghvi17** [comment]
PGFPlotsX can generate a PGFPlots spec in TeX code, so you can use the latest Pythontex master (to be safe, I don't know if they've fixed the Julia issues in TL 2019) with PGFPlotsX.  The reason I recommend it is that it provides a more native looking theme, along with access to all of PGFPlots' features, in a more familiar interface (for the reader who may not be familiar with Julia).

**Comment by asinghvi17** [comment]
The above comment should just work.  I believe you can also switch backends within the code?  Will have to test it though, since it's been a while since I used this.

**Comment by BeastyBlacksmith** [comment]
It indeed works, but only because it works with `PGFPlots.Plot`. Using recipes does not work.
However, I have a patch to fix this (see https://github.com/sisl/juliaplots.sty/pull/3).
Generally loading plotting packages in `support_code.jl` should be discouraged.
