### ISSUE TITLE
Declared option and PyPlot

### ISSUE THREAD

**Issue by evcastelani** [sisl/juliaplots.sty#5]
It seems to me that there is an error on line 28 of the file juliaplots.sty. It is missing one " \ ".  Other thing: the option PyPlot works fine ? In  my case it isn't work: 

Package luatex.def Error: File `myfile.pdf' not found: using draft setting.

Any tips?

Regards

**Comment by mykelk** [comment]
It looks like a slash got lost. I added it back in. Can you check whether it works for you now?

**Comment by evcastelani** [comment]
Yes, I had already corrected that. However, the image is not being generated by PyPlot. The following error occurs in the first lualatex compilation:

` LaTeX Warning: File myfile.pdf not found on input line 12.`
`! Package luatex.def Error: File myfile.pdf not found: using draft setting.`
`See the luatex.def package documentation for explanation.`
`Type  H <return>  for immediate help.`
` ...                                              `
` l.12 \plot{myfile}{width=3in} `

Do you have any suggestion?

PyPlot works fine using Julia REPL.

**Comment by mykelk** [comment]
I think I know how to fix it. I'll do it today.

**Comment by mykelk** [comment]
Did that do the trick for you?

**Comment by evcastelani** [comment]
Sorry for the delay to reply. Now  everything is working. But I had to install version 0.18 of Pythontex. With 0.16 it doesn't work. Thanks a lot by help me!

**Comment by mykelk** [comment]
I think it requires 0.17 or later.

**Comment by evcastelani** [comment]
Yes, you're right!
